/* eslint-disable @typescript-eslint/naming-convention */

import {ILanguage, LocalizationKeys, SupportedLanguages} from './language';

export class German implements ILanguage {
  language = SupportedLanguages.German;
  translations: LocalizationKeys = {
    Hello: 'Hallo',
    HelloFunction: (count: number) => count === 1 ? `Hallo, du bist alleine.` : `Hallo, ihr seid ${count} Personen`,
    login: 'Einloggen',
    register: 'Registrieren',
    registered: 'Registriert',
    SwitchLanguage: 'Sprache wechseln',
    MyTournaments: 'Meine Turniere',
    succRegComp: 'Anmeldung erfolgreich',
    errRegComp: 'Anmeldung fehlgeschlagen',
    registration: 'Anmeldung',
    competition: 'Wettkampf',
    groupPreference: 'Bevorzugte Gruppe',
    noPreference: 'keine Preferänz',
    forgotPassword: 'Passwort vergessen',
    sendResetLink: 'Sende Link zum zurücksetzen',

    edit: 'Bearbeiten',

    datesAndContacts: 'Daten und Kontakt',
    description: 'Beschreibung',
    until: 'bis',
    Tournamnet: 'Wettkampf',
    contact: 'Kontakt',
    participants: 'Teilnehmer',
    managedParticipants: 'Teilnehmer die Sie verwalten',

    title: 'Titel',
    phoneNumber: 'Telefonnummer',
    beginOfCompetition: 'Wettkampf Start',
    endOfCompetition: 'Wettkampf Ende',
    beginOfRegistration: 'Anmeldung offen ab',
    endOfRegistration: 'Anmeldeschluss',
    settings: 'Einstellungen',
    publish: 'Veröffentlichen',
    public: 'Öffentlich',
    onlyClubs: 'Nur Vereine',
    save: 'Speichern',

    meanStrategy: 'Durchschnitt',
    equalStrategy: 'Gleich',

    judge: 'Bewertungsrichter',

    time: 'Veranstaltungszeit',
    beginAtOrAfter: 'Austragungsdatum ab',
    registrationNotDone: 'Registrierung möglich',
    search: 'Suchen',

    calculateCompetitionResults: 'Endergebnisse berechnen',

    all: 'Alle',
    accepted: 'Akzeptiert',
    outstanding: 'Ausstehend',
    status: 'Status',
    action: 'Aktion',
    editStatus: 'Status ändern',
    editGradingGroup: 'Grading Group ändern',
    manageParticipants: 'Teilnehmer Verwalten',
    cancel: 'Abbrechen',
    oopsSomethingWentWrong: 'Ups, da ist wohl was schief gelaufen.',

    logout: 'Abmelden',
    importCSV: 'Neue Teammitglieder',
    teamName: 'Teamname',
    page: 'Seite',
    member: 'Teammitglied',
    clearAll: 'Alle löschen',
    genderMan: 'Männlich',
    genderWoman: 'Weiblich',
    genderOther: 'Divers',
    importCSVButton: 'Importieren als CSV',
    exportCSVButton: 'Exportieren als CSV',
    import: 'Importieren',
    team: 'Mannschaft',

    createTournament: 'Neuer Wettkampf',
    myResults: 'Meine Ergebnisse',
    myGradingSystems: 'Bewertungssysteme Verwalten',

    calendar: 'Kalender',

    importFlags: 'Flags zuweisen',
    flag: 'Flag',
    optional: 'optional',
    add: 'hinzufügen',
    delete: 'löschen',
    new: 'neu',
    create: 'erstellen',
    createFlag: 'neues Flag erstellen',
    selectAGroup: 'Wähle eine Gruppe',
    groupHasRegistrationReq: 'Diese Gruppe hat Registrierungsbedingungen',
    showGroupInformation: 'Gruppen Details anzeigen',
    assignAll: 'Alle zuweisen',
    groups: 'Gruppen',

    registerToAGroup: 'Registriere dich für eine Gruppe',
    close: 'Abbrechen',
    formula: 'Formel',
    chooseGradingGroup: 'Bewertungsgruppe auswählen',
    importGradingGroup: 'Bewertungsgruppe Aus Templates auswählen',
    createGradingSystem: 'Neue Bewertungssystem erstellen',
    onlyEditables: 'Nur Veränderbare',
    yes: 'Ja',
    no: 'Nein',
    others: 'Anderes',
    publicType: 'Typ',
    gradingGroup: 'Bewertungsgruppe',
    gradingSystems: 'Bewertungssysteme',
    manageTemplateGradingSystems: 'Bewertungssysteme Verwalten',
    publicTypeAll: 'Publik & Privat',
    publicTypePrivate: 'Privat',
    publicTypePublic: 'Publik',
    reset: 'Zurücksetzen',
    passwordResetLinkSent: 'Ein Link zum Zurücksetzen Ihres Passworts wurde an Ihre E-Mail Adresse gesandt.',
    enterValidMailForReset: 'Bitte geben Sie eine gültige E-Mail Adresse ein.',

    username: 'Benutzername / Email',
    firstname: 'Vorname',
    lastname: 'Nachname',
    password: 'Passwort',
    repeatPassword: 'Passwort wiederholen',
    passwordMinLength8: 'Ihr Passwort muss mindestens 8 Zeichen lang sein!',
    userSettings: 'Einstellungen',
    filePictureRestrictions: 'Nur .png, .jpeg oder .jpg, sowie <= 1 Megabyte',
    uploadCompetitionPictureDisclaimer: 'Hier können Sie ein Bild für das Turnier hochladen.',
    clearFileUpload: 'Datei neu wählen',
    changePassword: 'Passwort ändern',
    resetPassword: 'Passwort zurücksetzen',
    resetPasswordSuccess: 'Passwort erfolgreich zurückgesetzt!',
    resetPasswordError: 'Es wurde kein Benutzer mit dem angegebenen Reset-Token im System gefunden!',
    resetPasswordErrorLoggedIn: 'Sie können Ihr Passwort nicht zurücksetzen wenn Sie bereits eingeloggt sind!',
    resetPasswordErrorMalformedToken: 'Aufgrund eines ungültigen Reset-Tokens wurden Sie weitergeleitet!',
    passwordsMustMatch: 'Beide Passwörter müssen übereinstimmen!',
    changeUserPicture: 'Profilbild ändern',
    uploadUserPicture: 'Bild hochladen',
    dateOfBirth: 'Geburtstag',
    gender: `Geschlecht`,
    type: `Rolle`,

    regMemToComp: 'Registriere Mitgliere zu einem Wettkampf',
    searchAndSelectToRegister: 'Suche und wähle einen Wettkampf aus',
    registrationEnds: 'Registrierung endet',
    members: 'Mitglieder',
    membersPerPage: 'Mitglieder pro Seite',
    searchACompetition: 'Suche nach einem Wettkampf',
    back: 'Zurück',
    showRegistrationRequirements: 'Zeige Registrations-Voraussetzungen',
    addAnotherCondition: 'Weitere Bedingung hinzufügen',
    manageRegistrationConstraints: 'Verwalten Sie die Registrierungsbedingungen. ' +
      'Jemand kann sich anmelden, wenn alle Bedingungen erfüllt sind.',
    registerConstraints: 'Registrierungsbedingungen',
    noConstraints: 'Keine Bedingungen',
    constraints: 'Bedingungen',
    everybodyCanRegisterToThisGroup: 'Jeder kann sich für diese Gruppe anmelden.',
    age: 'Alter',
    equals: 'gleich',
    notEquals: 'ungleich',
    greaterThan: 'größer',
    greaterOrEqualsThan: 'größer gleich',
    lessThan: 'kleiner',
    lessOrEqualsThan: 'kleiner gleich',
    bornBefore: 'geboren vor',
    bornAfter: 'geboren nach',


    editTeam: 'Team bearbeiten',
    addRemoveFlags: 'Flags hinzufügen/löschen',

    liveResults: 'Live Ergebnisse',

    enter: (type: string) => `${type} eingeben...`,
    reEnter: (type: string) => `${type} wiederholen...`,
    getType: (type: string) => ({
      Participant: 'Teilnehmer:in',
      ClubManager: 'Vereinsverantwortliche:r',
      CompetitionManager: 'Turnier Manager:in',
    }[type]),
    getGender: (gender: string) => ({
      Female: 'Weiblich',
      Male: 'Männlich',
      Other: 'Divers',
    }[gender]),

    isRequired: (thing) => `${thing} wird benötigt!`,
    isMalformed: (thing) => `${thing} ist nicht gültige!`,
  };
}
